using NIU.ACH_AI.Application.DTOs;

namespace NIU.ACH_AI.Application.Interfaces
{
    /// <summary>
    /// Defines the contract for persisting responses generated by AI agents.
    /// </summary>
    public interface IAgentResponsePersistence
    {
        /// <summary>
        /// Saves a fully formed agent response record.
        /// </summary>
        /// <param name="response">The agent response record to persist.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        Task SaveAgentResponseAsync(
            AgentResponseRecord response,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Saves an agent response by extracting token usage from metadata and mapping properties internally.
        /// </summary>
        /// <param name="content">The text content of the response.</param>
        /// <param name="metadata">The metadata dictionary from the AI provider.</param>
        /// <param name="agentName">The name of the agent.</param>
        /// <param name="stepExecutionId">The ID of the step execution.</param>
        /// <param name="agentConfigurationId">The ID of the agent configuration.</param>
        /// <param name="turnNumber">The turn index in the conversation.</param>
        /// <param name="responseDuration">The duration of the response generation in milliseconds.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        Task SaveAgentResponseAsync(
            string content,
            IReadOnlyDictionary<string, object?>? metadata,
            string agentName,
            Guid stepExecutionId,
            Guid agentConfigurationId,
            int turnNumber,
            long responseDuration,
            CancellationToken cancellationToken = default);
    }
}
