// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NIU.ACH_AI.Infrastructure.Persistence.Models;

#nullable disable

namespace NIU.ACH_AI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ACHSagaDbContext))]
    [Migration("20260102210249_InitialSagaCreate")]
    partial class InitialSagaCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NIU.ACH_AI.Infrastructure.Persistence.Models.ExperimentState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("int");

                    b.Property<Guid?>("EvidenceStepExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HypothesisStepExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RefinedHypothesisStepExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerializedConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerializedInput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerializedResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("CorrelationId");

                    b.ToTable("ExperimentState");
                });
#pragma warning restore 612, 618
        }
    }
}
