using NIU.ACH_AI.Domain.Entities;

namespace NIU.ACH_AI.Infrastructure.Persistence.Repositories;

/// <summary>
/// Repository for hypothesis persistence operations.
/// Works exclusively with domain entities - no database models exposed.
/// </summary>
public interface IHypothesisRepository
{
    /// <summary>
    /// Saves a batch of hypotheses generated by AI for a given step execution.
    /// </summary>
    Task SaveBatchAsync(
        IEnumerable<Hypothesis> hypotheses,
        Guid stepExecutionId,
        bool isRefined,
        CancellationToken cancellationToken = default
        );

    /// <summary>
    /// Retrieves all hypotheses for a specific step execution.
    /// </summary>
    Task<List<Hypothesis>> GetByStepExecutionIdAsync(
        Guid stepExecutionId,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves a single hypothesis by its ID.
    /// </summary>
    Task<Hypothesis?> GetByIdAsync(
        Guid hypothesisId,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves only refined hypotheses for a step execution.
    /// </summary>
    Task<List<Hypothesis>> GetRefinedByStepExecutionIdAsync(
        Guid stepExecutionId,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Marks a hypothesis as refined in the database.
    /// </summary>
    Task MarkAsRefinedAsync(
        Guid hypothesisId,
        CancellationToken cancellationToken = default);
}
