CREATE TABLE [dbo].[AGENT_CONFIGURATIONS]
(
	[agent_configuration_id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [ach_step_workflow_id] UNIQUEIDENTIFIER NOT NULL, 
    [agent_name] NVARCHAR(50) NOT NULL, 
    [description] NVARCHAR(500) NOT NULL, 
    [instructions] NVARCHAR(MAX) NOT NULL, 
    [provider_id] UNIQUEIDENTIFIER NOT NULL, 
    [model_id] UNIQUEIDENTIFIER NOT NULL, 
    [created_at] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), 
    [updated_at] DATETIME2 NULL, 
    CONSTRAINT [FK_AGENT_CONFIGURATIONS_PROVIDERS] FOREIGN KEY ([provider_id]) REFERENCES [PROVIDERS]([provider_id]), 
    CONSTRAINT [FK_AGENT_CONFIGURATIONS_MODELS] FOREIGN KEY ([model_id]) REFERENCES [MODELS]([model_id])
)
