CREATE TABLE [dbo].[HYPOTHESES]
(
	[hypothesis_id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[step_execution_id] UNIQUEIDENTIFIER NOT NULL,
	[short_title] NVARCHAR(200) NOT NULL,
	[hypothesis_text] NVARCHAR(MAX) NOT NULL,
	[is_refined] BIT NOT NULL DEFAULT 0,
	[created_at] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	CONSTRAINT [FK_HYPOTHESES_STEP_EXECUTIONS] FOREIGN KEY ([step_execution_id]) REFERENCES [STEP_EXECUTIONS]([step_execution_id])
)
