CREATE TABLE [dbo].[PROVIDERS]
(
	[provider_id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [provider_name] NVARCHAR(50) NOT NULL, 
    [description] NVARCHAR(255) NULL, 
    [is_active] BIT NOT NULL DEFAULT 1, 
    [created_at] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
