/*
    Script: Add MS_Description extended properties for documentation
    Date: 2025-12-22
    Purpose: Add formal SQL Server documentation to all tables and key columns

    MS_Description extended properties appear in SQL Server Management Studio
    and other database tools, providing inline documentation for developers
    and database administrators.
*/

-- =====================================================================================
-- TABLE: ACH_STEPS
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Defines the steps in the Analysis of Competing Hypotheses (ACH) methodology. Steps can have substeps grouped by primary_ach_step.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'ACH_STEPS';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Primary key identifier for the ACH step',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'ACH_STEPS',
    @level2type = N'COLUMN', @level2name = 'ach_step_id';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Name of the ACH step (e.g., "Hypothesis Brainstorming", "Evidence Evaluation")',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'ACH_STEPS',
    @level2type = N'COLUMN', @level2name = 'step_name';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Execution order of this step within the ACH methodology',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'ACH_STEPS',
    @level2type = N'COLUMN', @level2name = 'step_order';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Groups substeps under a primary ACH step (e.g., 1a, 1b, 1c all have primary_ach_step=1). This is NOT a foreign key.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'ACH_STEPS',
    @level2type = N'COLUMN', @level2name = 'primary_ach_step';
GO

-- =====================================================================================
-- TABLE: AGENT_CONFIGURATIONS
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Agent configurations define which AI agents are used in step executions, including their instructions, model, and provider settings.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'AGENT_CONFIGURATIONS';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'References the step execution this agent configuration belongs to. Was previously named ach_step_workflow_id.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'AGENT_CONFIGURATIONS',
    @level2type = N'COLUMN', @level2name = 'step_execution_id';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Snapshot of agent name at configuration time. Denormalized for historical analysis.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'AGENT_CONFIGURATIONS',
    @level2type = N'COLUMN', @level2name = 'agent_name';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'System prompt/instructions provided to the AI agent.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'AGENT_CONFIGURATIONS',
    @level2type = N'COLUMN', @level2name = 'instructions';
GO

-- =====================================================================================
-- TABLE: AGENT_RESPONSES
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Captures outputs from AI agents during step executions, including token counts, response content, and performance metrics.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'AGENT_RESPONSES';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Number of input tokens sent to the model API.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'AGENT_RESPONSES',
    @level2type = N'COLUMN', @level2name = 'input_token_count';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Number of output tokens generated by the model.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'AGENT_RESPONSES',
    @level2type = N'COLUMN', @level2name = 'output_token_count';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Response time in milliseconds from API call to completion.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'AGENT_RESPONSES',
    @level2type = N'COLUMN', @level2name = 'response_duration';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Turn number in multi-turn conversations (null for single-turn).',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'AGENT_RESPONSES',
    @level2type = N'COLUMN', @level2name = 'turn_number';
GO

-- =====================================================================================
-- TABLE: EVALUATION_SCORES
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Reference table for evidence-hypothesis evaluation scores (e.g., Consistent, Inconsistent, Neutral).',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVALUATION_SCORES';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Name of the evaluation score (e.g., "Consistent", "Inconsistent", "Neutral").',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVALUATION_SCORES',
    @level2type = N'COLUMN', @level2name = 'score_name';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Numeric value for scoring calculations (e.g., +1 for Consistent, -1 for Inconsistent, 0 for Neutral).',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVALUATION_SCORES',
    @level2type = N'COLUMN', @level2name = 'score_value';
GO

-- =====================================================================================
-- TABLE: EVIDENCE
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Stores facts and assumptions extracted from source material during ACH analysis. Each piece of evidence is categorized and linked to its source step execution.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVIDENCE';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'The evidence claim or statement extracted from the source material.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVIDENCE',
    @level2type = N'COLUMN', @level2name = 'claim';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Verbatim quote from source material supporting this evidence claim.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVIDENCE',
    @level2type = N'COLUMN', @level2name = 'reference_snippet';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Additional context, credibility notes, or analyst comments about this evidence.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVIDENCE',
    @level2type = N'COLUMN', @level2name = 'notes';
GO

-- =====================================================================================
-- TABLE: EVIDENCE_HYPOTHESIS_EVALUATIONS
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Forms the core ACH matrix: evaluates how each piece of evidence relates to each hypothesis (Consistent, Inconsistent, or Neutral).',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVIDENCE_HYPOTHESIS_EVALUATIONS';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Step execution that created this evaluation. Denormalized for query performance.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVIDENCE_HYPOTHESIS_EVALUATIONS',
    @level2type = N'COLUMN', @level2name = 'step_execution_id';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Explanation of why this evaluation score was assigned.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVIDENCE_HYPOTHESIS_EVALUATIONS',
    @level2type = N'COLUMN', @level2name = 'rationale';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Numeric confidence score (0.0000 to 1.0000) in this evaluation.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVIDENCE_HYPOTHESIS_EVALUATIONS',
    @level2type = N'COLUMN', @level2name = 'confidence_score';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Explanation of the confidence score level.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVIDENCE_HYPOTHESIS_EVALUATIONS',
    @level2type = N'COLUMN', @level2name = 'confidence_rationale';
GO

-- =====================================================================================
-- TABLE: EVIDENCE_TYPES
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Reference table categorizing types of evidence (e.g., Fact, Assumption, Observation).',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EVIDENCE_TYPES';
GO

-- =====================================================================================
-- TABLE: EXPERIMENTS
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Represents complete ACH analysis runs. Each experiment analyzes a scenario using a specific configuration of steps and agents.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EXPERIMENTS';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Key Intelligence Question (KIQ) being analyzed in this experiment.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'EXPERIMENTS',
    @level2type = N'COLUMN', @level2name = 'kiq';
GO

-- =====================================================================================
-- TABLE: HYPOTHESES
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Stores possible answers to the Key Intelligence Question, generated during the hypothesis brainstorming step of ACH.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'HYPOTHESES';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Brief summary title of the hypothesis.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'HYPOTHESES',
    @level2type = N'COLUMN', @level2name = 'short_title';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Full hypothesis statement.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'HYPOTHESES',
    @level2type = N'COLUMN', @level2name = 'hypothesis_text';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Whether this hypothesis passed the refinement step (0=unrefined, 1=refined).',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'HYPOTHESES',
    @level2type = N'COLUMN', @level2name = 'is_refined';
GO

-- =====================================================================================
-- TABLE: MODELS
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Defines AI models and their pricing information. Used to calculate costs based on token usage in agent responses.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'MODELS';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Model identifier (e.g., "gpt-4", "claude-3-opus", "gpt-4-turbo").',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'MODELS',
    @level2type = N'COLUMN', @level2name = 'model_name';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Cost per input token in USD. Precision: DECIMAL(10,8) to support micro-pricing.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'MODELS',
    @level2type = N'COLUMN', @level2name = 'input_token_cost';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Cost per cached input token in USD (if model supports prompt caching).',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'MODELS',
    @level2type = N'COLUMN', @level2name = 'cached_input_token_cost';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Cost per output token in USD.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'MODELS',
    @level2type = N'COLUMN', @level2name = 'output_token_cost';
GO

-- =====================================================================================
-- TABLE: ORCHESTRATION_TYPES
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Defines how agents are orchestrated in step executions (e.g., Sequential, Parallel, RoundRobin).',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'ORCHESTRATION_TYPES';
GO

-- =====================================================================================
-- TABLE: PROVIDERS
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'AI service providers (e.g., OpenAI, Anthropic, Google). Links to MODELS table.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'PROVIDERS';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Whether this provider is currently enabled for use in experiments.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'PROVIDERS',
    @level2type = N'COLUMN', @level2name = 'is_active';
GO

-- =====================================================================================
-- TABLE: SCENARIOS
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Test scenarios containing context/background information for experiments. Each scenario represents a situation to be analyzed using ACH.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'SCENARIOS';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Full scenario text/background information for ACH analysis.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'SCENARIOS',
    @level2type = N'COLUMN', @level2name = 'context';
GO

-- =====================================================================================
-- TABLE: STEP_EXECUTIONS
-- =====================================================================================

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Tracks individual ACH step runs within an experiment. Includes configuration snapshot, timing, status, and error information.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'STEP_EXECUTIONS';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Snapshot of step name at execution time. Denormalized for historical analysis.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'STEP_EXECUTIONS',
    @level2type = N'COLUMN', @level2name = 'ach_step_name';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Instructions/prompt provided to agents in this step execution.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'STEP_EXECUTIONS',
    @level2type = N'COLUMN', @level2name = 'task_instructions';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Execution status: NotStarted, Running, Completed, Failed, or Cancelled.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'STEP_EXECUTIONS',
    @level2type = N'COLUMN', @level2name = 'execution_status';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Full error message/stack trace if execution failed.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'STEP_EXECUTIONS',
    @level2type = N'COLUMN', @level2name = 'error_message';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Categorized error type for analysis (e.g., RateLimitError, TimeoutError, ValidationError).',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'STEP_EXECUTIONS',
    @level2type = N'COLUMN', @level2name = 'error_type';
GO

EXEC sp_addextendedproperty
    @name = N'MS_Description', @value = N'Number of retry attempts for this execution.',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE',  @level1name = 'STEP_EXECUTIONS',
    @level2type = N'COLUMN', @level2name = 'retry_count';
GO

PRINT 'Successfully added MS_Description documentation to all tables and key columns';
GO
